project_name: go-grc

before:
  hooks:
    - go mod tidy

builds:
  - main: ./cmd/grc
    id: "grc"
    binary: grc
    env:
      - CGO_ENABLED=0
    goos:
      - linux
      - darwin
      - windows
    goarch:
      - amd64
      - arm64
    ldflags:
      - -s -w -X main.Version={{.Version}} -X main.BuildTime={{.Date}}

archives:
  - format: tar.gz
    name_template: >-
      {{ .ProjectName }}_
      {{- title .Os }}_
      {{- if eq .Arch "amd64" }}x86_64
      {{- else if eq .Arch "386" }}i386
      {{- else }}{{ .Arch }}{{ end }}
    format_overrides:
      - goos: windows
        format: zip

checksum:
  name_template: 'checksums.txt'

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - '^chore:'
      - Merge pull request
      - Merge branch

dockers:
  - image_templates:
      - "ghcr.io/sirosfoundation/go-grc:{{ .Version }}-amd64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/amd64"
      - "--build-arg=VERSION={{ .Version }}"
      - "--build-arg=BUILD_TIME={{ .Date }}"
    goarch: amd64
  - image_templates:
      - "ghcr.io/sirosfoundation/go-grc:{{ .Version }}-arm64"
    use: buildx
    build_flag_templates:
      - "--platform=linux/arm64"
      - "--build-arg=VERSION={{ .Version }}"
      - "--build-arg=BUILD_TIME={{ .Date }}"
    goarch: arm64

docker_manifests:
  - name_template: "ghcr.io/sirosfoundation/go-grc:{{ .Version }}"
    image_templates:
      - "ghcr.io/sirosfoundation/go-grc:{{ .Version }}-amd64"
      - "ghcr.io/sirosfoundation/go-grc:{{ .Version }}-arm64"
  - name_template: "ghcr.io/sirosfoundation/go-grc:latest"
    image_templates:
      - "ghcr.io/sirosfoundation/go-grc:{{ .Version }}-amd64"
      - "ghcr.io/sirosfoundation/go-grc:{{ .Version }}-arm64"
